### ISSUE TITLE
"improve" branch

### ISSUE THREAD

**Issue by jsteinaker** [humdingerb/ubertuber#21]
Hi, I was doing a small mod in UberTuber (basically just add an OptionPopUp to select the file format), and only after I finished I've noticed the "improve" branch, with some important changes in the main classes, to use CommandPipe.

My question is: are you still going that way? I've noticed the "improve" branch compiles but fails when trying to download a video. When started from Terminal, you can see that apparently one of the arguments gets corrupted somehow, and so youtube-dl fails. I've tried with or without the "format" argument, and what happens, if it isn't present, is that the next argument is not understood.

For the moment, I'll just leave the mod on the master branch, where it works. But I'll gladly move that to "improve", provided that branch is still relevant and we can figure out why is failing.

Thanks.

**Comment by humdingerb** [comment]
Hi Javier,

I had the same issues with youtube-dl failing in the "improve" branch. Never found out why, and haven't looked at it since. In fact, I always thought UberTuber was a big fat, barely working hack and don't plan on doing anything further with it.

I switched to a simple script to double-click on the desktop. It uses youtube-dl for youtube-URLs and wget for all else:

```
#!/bin/sh

cd ~/Desktop
clip=$(clipboard -p)

if [[ $clip == *youtube* || $clip == "*youtu.be*" ]] ; then
	filename=$(youtube-dl --restrict-filenames --no-part --no-cache-dir --format best --get-filename "$clip")
	youtube-dl --continue --restrict-filenames --no-part --no-cache-dir --format best "$clip"
	addattr META:url "$clip" "$filename"
	mimeset -F "$filename"
else
	filename=$(basename "$clip")
	wget "$clip"
	addattr META:url "$clip" "$filename"
	mimeset -F "$filename"
fi
```

If you're interested in continuing UberTuber (like selection quality, format, etc.), I can either merge your pull-requests or simply transfer the repo to you.

**Comment by jsteinaker** [comment]
Good to know. I'll start working on that, if I ever get something serious done I'll send you a PR.

Closing this.
